name = "cloud-mail"
main = "src/index.ts"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "KV", id = "你的KV ID" }
]

d1_databases = [
  { binding = "DB", database_name = "cloudmail", database_id = "你的D1 ID" }
]
